-- ════════════════════════════════════════════════════════════════
-- FinFlow · Postgres schema (GENERATED — do not edit by hand)
--
-- Source of truth: supabase/migrations/*.sql
-- Regenerated by:  node scripts/db-migrations-check.mjs --fix
-- CI gate:         scripts/automation-run.mjs · "db-migrations"
--
-- To change the schema:
--   1. Add an additive migration at supabase/migrations/<timestamp>_<name>.sql
--   2. Run `node scripts/db-migrations-check.mjs --fix` to refresh this file
--   3. Apply the migration to staging (e.g. via the Supabase MCP
--      `apply_migration` tool) and the security advisor, per
--      docs/TEST_GOVERNANCE.md §4
-- ════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/00000000000001_production_state_baseline.sql
-- ─────────────────────────────────────────────────────────────────────
-- ════════════════════════════════════════════════════════════════
-- FinFlow · Production state baseline (TD-20)
--
-- Captured: 2026-05-28 via Supabase MCP introspection against the
--           dmxqkvploojokffuhxnz Supabase project.
--
-- This file represents the **actual** shape of the production database
-- as it existed on the date above — the result of 13 migrations the
-- team applied via the Supabase Dashboard's SQL editor (tracked in
-- `supabase_migrations.schema_migrations` as `finflow_v4_1_initial_schema`
-- through `v646_admin_ai_usage_summary`). NONE of the partial migrations
-- that previously lived in this directory under the names
--   00000000000000_initial_schema.sql
--   20260523060000_admin_roles_and_dashboard_kpis.sql
--   20260524070000_budgets_add_period.sql
--   20260524071000_audit_triggers.sql
--   20260524073000_replace_all_rpc.sql
--   20260524075000_subscriptions_table_and_kpis.sql
--   20260524076000_content_items_table_and_kpis.sql
--   20260524077000_admin_rpcs.sql
-- have ever actually been applied to production. They remain in the
-- repo with a SUPERSEDED banner as design-intent records, but this
-- file is the new source of truth.
--
-- See TECH_DEBT.md TD-20 for the full reconciliation story and
-- db/MIGRATIONS.md for the workflow going forward.
--
-- Order: extensions → tables → foreign keys → indexes → functions →
--        triggers → RLS enable → RLS policies → grants.
-- ════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. EXTENSIONS ───────────────────────────────────────────────
create extension if not exists pgcrypto    schema extensions;
create extension if not exists pg_trgm     schema public;
create extension if not exists "uuid-ossp" schema extensions;

-- ── 2. TABLES ───────────────────────────────────────────────────
-- Created in dependency order. Foreign keys added after all tables
-- exist so the order constraint is purely informational.

-- profiles
create table if not exists profiles (
  id                uuid primary key,
  display_name      text,
  avatar_url        text,
  default_currency  text not null default 'USD',
  language          text not null default 'en',
  date_format       text not null default 'us',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- households
create table if not exists households (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  type            text not null check (type in ('family','business','personal','shared')),
  base_currency   text not null default 'USD',
  language        text default 'en',
  payoff_strategy text default 'avalanche' check (payoff_strategy in ('avalanche','snowball')),
  extra_payment   numeric default 0,
  created_by      uuid not null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- memberships
create table if not exists memberships (
  id              uuid primary key default gen_random_uuid(),
  household_id    uuid not null,
  user_id         uuid,
  role            text not null check (role in ('owner','admin','member','viewer','child')),
  display_name    text not null,
  household_role  text check (household_role in ('primary','partner','child','elder')),
  joined_at       timestamptz not null default now()
);

-- invitations
create table if not exists invitations (
  id              uuid primary key default gen_random_uuid(),
  household_id    uuid not null,
  invited_email   text not null,
  invited_by      uuid not null,
  role            text not null check (role in ('admin','member','viewer','child')),
  household_role  text,
  token           text not null unique default encode(extensions.gen_random_bytes(24), 'base64'),
  expires_at      timestamptz not null default (now() + interval '14 days'),
  accepted_at     timestamptz,
  created_at      timestamptz not null default now()
);

-- transactions
create table if not exists transactions (
  id              uuid primary key default gen_random_uuid(),
  household_id    uuid not null,
  created_by      uuid,
  member_id       uuid,
  type            text not null check (type in ('income','expense','investment','transfer')),
  amount          numeric not null check (amount > 0),
  currency        text not null default 'USD',
  date            date not null,
  description     text not null,
  category        text not null,
  note            text,
  recurring       text check (recurring in ('','weekly','monthly','yearly')),
  attachment_url  text,
  extras          jsonb,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz
);

-- budgets
create table if not exists budgets (
  id              uuid primary key default gen_random_uuid(),
  household_id    uuid not null,
  category        text not null,
  monthly_limit   numeric not null check (monthly_limit > 0),
  currency        text not null default 'USD',
  color           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz
);

-- goals
create table if not exists goals (
  id              uuid primary key default gen_random_uuid(),
  household_id    uuid not null,
  type            text not null check (type in ('emergency','savings','debt','investment','purchase','custom')),
  name            text not null,
  target_amount   numeric not null check (target_amount > 0),
  current_amount  numeric not null default 0,
  currency        text not null default 'USD',
  deadline        date,
  completed       boolean not null default false,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz
);

-- debts
create table if not exists debts (
  id              uuid primary key default gen_random_uuid(),
  household_id    uuid not null,
  type            text not null,
  name            text not null,
  lender          text,
  account_last4   text check (length(account_last4) <= 4),
  principal       numeric,
  current_balance numeric not null check (current_balance >= 0),
  interest_rate   numeric not null check (interest_rate >= 0 and interest_rate < 100),
  minimum_payment numeric not null check (minimum_payment >= 0),
  due_date        date,
  currency        text not null default 'USD',
  extras          jsonb,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz
);

-- assets
create table if not exists assets (
  id              uuid primary key default gen_random_uuid(),
  household_id    uuid not null,
  type            text not null,
  name            text not null,
  value           numeric not null check (value >= 0),
  currency        text not null default 'USD',
  liquidity       text not null check (liquidity in ('liquid','short','long')),
  note            text,
  last_updated    date,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz
);

-- exchange_rates  (composite PK)
create table if not exists exchange_rates (
  household_id    uuid not null,
  currency_code   text not null,
  rate_to_usd     numeric not null check (rate_to_usd > 0),
  updated_at      timestamptz not null default now(),
  primary key (household_id, currency_code)
);

-- activity_log
create table if not exists activity_log (
  id              uuid primary key default gen_random_uuid(),
  household_id    uuid not null,
  actor_id        uuid,
  action          text not null check (action in ('created','updated','deleted','invited','accepted','removed','role_changed','transferred')),
  entity_type     text not null,
  entity_id       uuid,
  changes         jsonb,
  created_at      timestamptz not null default now()
);

-- admin_roles  (user_id is PK; no surrogate id)
create table if not exists admin_roles (
  user_id         uuid primary key,
  role            text not null check (role in ('super','roles','content')),
  granted_by      uuid,
  granted_at      timestamptz not null default now()
);

-- content_items
create table if not exists content_items (
  id              uuid primary key default gen_random_uuid(),
  slug            text not null unique,
  title           text not null,
  summary         text,
  body            text not null,
  topic           text not null check (topic in ('debt','tax','investment','budgeting','savings','retirement')),
  status          text not null default 'draft' check (status in ('draft','review','published','archived')),
  author_id       uuid,
  author_name     text not null,
  read_minutes    integer not null default 3,
  cover_emoji     text default '📰',
  published_at    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- content_favorites  (composite PK)
create table if not exists content_favorites (
  user_id         uuid not null,
  content_id      uuid not null,
  created_at      timestamptz not null default now(),
  primary key (user_id, content_id)
);

-- subscriptions
create table if not exists subscriptions (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null,
  household_id    uuid,
  tier            text not null check (tier in ('free','family','premium','enterprise')),
  status          text not null check (status in ('active','past_due','canceled','trialing')),
  monthly_amount  numeric not null default 0,
  currency        text not null default 'USD',
  started_at      timestamptz not null default now(),
  renews_at       timestamptz,
  canceled_at     timestamptz,
  failure_count   integer not null default 0,
  stripe_sub_id   text unique,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- category_classifications  (categories aren't household-scoped; this is system metadata)
create table if not exists category_classifications (
  category        text primary key,
  classification  text not null check (classification in ('need','want')),
  label           text,
  updated_at      timestamptz not null default now()
);

-- ai_usage  (privacy-safe: no message content; only intent + sentiment + length)
create table if not exists ai_usage (
  id              uuid primary key default gen_random_uuid(),
  household_id    uuid,
  user_id         uuid default auth.uid(),
  ts              timestamptz not null default now(),
  surface         text not null default 'chat',
  intent          text,
  sentiment       text check (sentiment in ('positive','neutral','negative')),
  sentiment_score numeric,
  message_len     integer
);

-- ── 3. FOREIGN KEY CONSTRAINTS ──────────────────────────────────
-- Added after all tables exist. Names match what's in production so a
-- diff against `pg_constraint` is a no-op when applied to a fresh DB.

alter table profiles
  add constraint profiles_id_fkey foreign key (id) references auth.users(id) on delete cascade;

alter table households
  add constraint households_created_by_fkey foreign key (created_by) references auth.users(id);

alter table memberships
  add constraint memberships_household_id_fkey foreign key (household_id) references households(id) on delete cascade,
  add constraint memberships_user_id_fkey      foreign key (user_id)      references auth.users(id)  on delete cascade;

alter table invitations
  add constraint invitations_household_id_fkey foreign key (household_id) references households(id) on delete cascade,
  add constraint invitations_invited_by_fkey   foreign key (invited_by)   references auth.users(id);

alter table transactions
  add constraint transactions_household_id_fkey foreign key (household_id) references households(id) on delete cascade,
  add constraint transactions_created_by_fkey   foreign key (created_by)   references auth.users(id),
  add constraint transactions_member_id_fkey    foreign key (member_id)    references memberships(id) on delete set null;

alter table budgets
  add constraint budgets_household_id_fkey foreign key (household_id) references households(id) on delete cascade;

alter table goals
  add constraint goals_household_id_fkey foreign key (household_id) references households(id) on delete cascade;

alter table debts
  add constraint debts_household_id_fkey foreign key (household_id) references households(id) on delete cascade;

alter table assets
  add constraint assets_household_id_fkey foreign key (household_id) references households(id) on delete cascade;

alter table exchange_rates
  add constraint exchange_rates_household_id_fkey foreign key (household_id) references households(id) on delete cascade;

alter table activity_log
  add constraint activity_log_household_id_fkey foreign key (household_id) references households(id) on delete cascade,
  add constraint activity_log_actor_id_fkey     foreign key (actor_id)     references auth.users(id);

alter table admin_roles
  add constraint admin_roles_user_id_fkey    foreign key (user_id)    references auth.users(id) on delete cascade,
  add constraint admin_roles_granted_by_fkey foreign key (granted_by) references auth.users(id) on delete set null;

alter table content_items
  add constraint content_items_author_id_fkey foreign key (author_id) references auth.users(id) on delete set null;

alter table content_favorites
  add constraint content_favorites_user_id_fkey    foreign key (user_id)    references auth.users(id)     on delete cascade,
  add constraint content_favorites_content_id_fkey foreign key (content_id) references content_items(id) on delete cascade;

alter table subscriptions
  add constraint subscriptions_user_id_fkey      foreign key (user_id)      references auth.users(id)  on delete cascade,
  add constraint subscriptions_household_id_fkey foreign key (household_id) references households(id)  on delete set null;

alter table ai_usage
  add constraint ai_usage_household_id_fkey foreign key (household_id) references households(id) on delete cascade,
  add constraint ai_usage_user_id_fkey      foreign key (user_id)      references auth.users(id) on delete set null;

-- ── 4. INDEXES ──────────────────────────────────────────────────
create index if not exists activity_household_time_idx     on activity_log(household_id, created_at desc);
create index if not exists ai_usage_household_idx          on ai_usage(household_id);
create index if not exists ai_usage_ts_idx                 on ai_usage(ts);
create index if not exists ai_usage_user_idx               on ai_usage(user_id);
create unique index if not exists budgets_household_category_uniq on budgets(household_id, category) where (deleted_at is null);
create index if not exists content_items_status_pubdate_idx on content_items(status, published_at desc);
create index if not exists content_items_topic_idx          on content_items(topic);
create index if not exists households_created_by_idx       on households(created_by);
create index if not exists invitations_email_idx           on invitations(invited_email) where (accepted_at is null);
create index if not exists invitations_token_idx           on invitations(token) where (accepted_at is null);
create index if not exists memberships_household_idx       on memberships(household_id);
create index if not exists memberships_user_idx            on memberships(user_id);
create index if not exists subscriptions_status_idx        on subscriptions(status);
create index if not exists subscriptions_user_idx          on subscriptions(user_id);
create index if not exists txns_household_cat_idx          on transactions(household_id, category) where (deleted_at is null);
create index if not exists txns_household_date_idx         on transactions(household_id, date desc) where (deleted_at is null);
create index if not exists txns_household_member_idx       on transactions(household_id, member_id) where (deleted_at is null);
create index if not exists txns_updated_idx                on transactions(household_id, updated_at);

-- ── 5. FUNCTIONS ────────────────────────────────────────────────
-- Captured verbatim from production via pg_get_functiondef().

create or replace function public.set_updated_at()
  returns trigger language plpgsql set search_path to 'public'
as $$ begin new.updated_at = now(); return new; end; $$;

create or replace function public.touch_updated_at()
  returns trigger language plpgsql
as $$ begin new.updated_at = now(); return new; end; $$;

create or replace function public.is_member(h_id uuid)
  returns boolean language sql stable security definer set search_path to 'public'
as $$ select exists (select 1 from memberships where household_id = h_id and user_id = auth.uid()); $$;

create or replace function public.role_in(h_id uuid)
  returns text language sql stable security definer set search_path to 'public'
as $$ select role from memberships where household_id = h_id and user_id = auth.uid() limit 1; $$;

create or replace function public.is_admin(min_role text default null)
  returns boolean language sql stable security definer set search_path to 'public'
as $$
  select exists (
    select 1 from admin_roles
    where user_id = auth.uid()
      and case
        when min_role is null     then true
        when min_role = 'super'   then role = 'super'
        when min_role = 'roles'   then role in ('super','roles')
        when min_role = 'content' then role in ('super','content')
        else false
      end
  );
$$;

create or replace function public.handle_new_user()
  returns trigger language plpgsql security definer set search_path to 'public'
as $$
declare v_display_name text;
begin
  v_display_name := coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1));
  insert into profiles (id, display_name) values (new.id, v_display_name);
  insert into households (name, type, base_currency, created_by) values ('My Household', 'personal', 'USD', new.id);
  return new;
end; $$;

create or replace function public.handle_new_household()
  returns trigger language plpgsql security definer set search_path to 'public'
as $$
begin
  insert into memberships (household_id, user_id, role, display_name, household_role)
  values (new.id, new.created_by, 'owner',
          coalesce((select display_name from profiles where id = new.created_by), 'Owner'),
          'primary');
  return new;
end; $$;

create or replace function public.accept_invitation(invite_token text)
  returns jsonb language plpgsql security definer set search_path to 'public'
as $$
declare inv record; caller_email text; new_membership_id uuid;
begin
  if auth.uid() is null then raise exception 'Must be signed in to accept an invitation'; end if;
  select email into caller_email from auth.users where id = auth.uid();
  select * into inv from invitations where token = invite_token and accepted_at is null limit 1;
  if inv is null then raise exception 'Invitation not found or already accepted'; end if;
  if inv.expires_at < now() then raise exception 'Invitation expired'; end if;
  if lower(inv.invited_email) <> lower(caller_email) then
    raise exception 'Invitation was sent to %, but you are signed in as %', inv.invited_email, caller_email;
  end if;
  if exists (select 1 from memberships where household_id = inv.household_id and user_id = auth.uid()) then
    update invitations set accepted_at = now() where id = inv.id;
    return jsonb_build_object('household_id', inv.household_id, 'already_member', true);
  end if;
  insert into memberships (household_id, user_id, role, display_name, household_role)
  values (inv.household_id, auth.uid(), inv.role,
          coalesce((select display_name from profiles where id = auth.uid()), split_part(caller_email, '@', 1)),
          inv.household_role)
  returning id into new_membership_id;
  update invitations set accepted_at = now() where id = inv.id;
  insert into activity_log (household_id, actor_id, action, entity_type, entity_id)
  values (inv.household_id, auth.uid(), 'accepted', 'invitation', inv.id);
  return jsonb_build_object('household_id', inv.household_id, 'membership_id', new_membership_id, 'role', inv.role);
end; $$;

create or replace function public.accept_invitation(invite_token uuid)
  returns jsonb language plpgsql security definer
as $$
declare inv invitations%rowtype; existing memberships%rowtype; mem_id uuid;
begin
  select * into inv from invitations where token = invite_token and accepted_at is null and expires_at > now();
  if not found then raise exception 'invitation_invalid_or_expired'; end if;
  select * into existing from memberships where household_id = inv.household_id and user_id = auth.uid();
  if found then
    return jsonb_build_object('household_id', inv.household_id, 'membership_id', existing.id, 'role', existing.role, 'already_member', true);
  end if;
  insert into memberships (household_id, user_id, role, display_name, household_role)
  select inv.household_id, auth.uid(), inv.role,
    coalesce((select display_name from profiles where id = auth.uid()),
             split_part((select email from auth.users where id = auth.uid()), '@', 1)),
    'member'
  returning id into mem_id;
  update invitations set accepted_at = now() where id = inv.id;
  return jsonb_build_object('household_id', inv.household_id, 'membership_id', mem_id, 'role', inv.role, 'already_member', false);
end; $$;

create or replace function public.leave_household(h_id uuid)
  returns void language plpgsql security definer
as $$
declare owner_count int;
begin
  select count(*) into owner_count from memberships where household_id = h_id and role = 'owner';
  if owner_count = 1 and (select role from memberships where household_id = h_id and user_id = auth.uid()) = 'owner' then
    raise exception 'last_owner_cannot_leave';
  end if;
  delete from memberships where household_id = h_id and user_id = auth.uid();
end; $$;

create or replace function public.transfer_ownership(h_id uuid, to_user uuid)
  returns void language plpgsql security definer
as $$
begin
  if (select role from memberships where household_id = h_id and user_id = auth.uid()) <> 'owner' then
    raise exception 'only_owner_can_transfer';
  end if;
  update memberships set role = 'owner' where household_id = h_id and user_id = to_user;
  update memberships set role = 'admin' where household_id = h_id and user_id = auth.uid();
end; $$;

create or replace function public.admin_dashboard_kpis()
  returns jsonb language plpgsql stable security definer set search_path to 'public', 'auth'
as $$
declare
  total_users int; total_households int; multi_member_pct numeric;
  active_7d int; active_households_7d int; signups_7d int; signups_30d int;
  total_txns int; txns_7d int; published_articles int; total_favorites int;
  paid_subscriptions int; mrr numeric;
begin
  if not public.is_admin('roles') then raise exception 'forbidden'; end if;
  select count(*) into total_users      from auth.users;
  select count(*) into total_households from households;
  select count(*) into total_txns       from transactions;
  select count(*) into signups_7d  from auth.users where created_at > now() - interval '7 days';
  select count(*) into signups_30d from auth.users where created_at > now() - interval '30 days';
  select count(distinct m.user_id) into active_7d from memberships m
    join auth.users u on u.id = m.user_id where u.last_sign_in_at > now() - interval '7 days';
  select count(distinct t.household_id) into active_households_7d from transactions t
    where t.created_at > now() - interval '7 days';
  select case when total_households > 0
    then round(100.0 * count(*) filter (where member_count >= 2) / total_households, 1) else 0 end
    into multi_member_pct
    from (select household_id, count(*) as member_count from memberships group by household_id) t;
  select count(*) into txns_7d from transactions where created_at > now() - interval '7 days';
  select count(*) into published_articles from content_items where status = 'published';
  select count(*) into total_favorites    from content_favorites;
  select count(*), coalesce(sum(monthly_amount) filter (where status='active'), 0)
    into paid_subscriptions, mrr from subscriptions where tier <> 'free';
  return jsonb_build_object(
    'totalUsers', total_users, 'totalHouseholds', total_households,
    'multiMemberPct', multi_member_pct, 'activeUsers7d', active_7d,
    'activeHouseholds7d', active_households_7d, 'signups7d', signups_7d,
    'signups30d', signups_30d, 'totalTransactions', total_txns,
    'transactions7d', txns_7d, 'publishedArticles', published_articles,
    'contentFavorites', total_favorites, 'paidSubscriptions', paid_subscriptions,
    'mrr', mrr, 'computedAt', now());
end; $$;

create or replace function public.admin_list_users()
  returns table(id uuid, email text, display_name text, email_confirmed boolean,
                created_at timestamptz, last_sign_in_at timestamptz,
                household_count integer, is_admin boolean, admin_role text)
  language sql stable security definer set search_path to 'public', 'auth'
as $$
  select u.id, u.email, p.display_name, (u.email_confirmed_at is not null) as email_confirmed,
         u.created_at, u.last_sign_in_at,
         coalesce((select count(*)::int from memberships m where m.user_id = u.id), 0) as household_count,
         (a.user_id is not null) as is_admin, a.role as admin_role
  from auth.users u
  left join public.profiles p    on p.id = u.id
  left join public.admin_roles a on a.user_id = u.id
  where public.is_admin('roles')
  order by u.created_at desc;
$$;

create or replace function public.admin_weekly_trend(weeks integer default 12)
  returns table(week_start date, signups integer, active_users integer, new_txns integer)
  language sql stable security definer set search_path to 'public', 'auth'
as $$
  with wks as (
    select generate_series(
      date_trunc('week', now())::date - (weeks - 1) * interval '7 days',
      date_trunc('week', now())::date,
      interval '7 days')::date as week_start
  )
  select w.week_start,
    (select count(*)::int from auth.users where created_at >= w.week_start and created_at < w.week_start + 7) as signups,
    (select count(distinct u.id)::int from auth.users u where u.last_sign_in_at >= w.week_start and u.last_sign_in_at < w.week_start + 7) as active_users,
    (select count(*)::int from transactions where created_at >= w.week_start and created_at < w.week_start + 7) as new_txns
  from wks w
  where public.is_admin('roles')
  order by w.week_start;
$$;

create or replace function public.admin_ai_usage_summary()
  returns jsonb language plpgsql security definer set search_path to 'public'
as $$
declare result jsonb;
begin
  if not public.is_admin('content') then raise exception 'forbidden: admin role required'; end if;
  select jsonb_build_object(
    'total',  (select count(*) from ai_usage),
    'users',  (select count(distinct user_id) from ai_usage),
    'last7',  (select count(*) from ai_usage where ts > now() - interval '7 days'),
    'last30', (select count(*) from ai_usage where ts > now() - interval '30 days'),
    'byIntent', (select coalesce(jsonb_object_agg(intent, c), '{}'::jsonb)
                 from (select coalesce(intent,'other') as intent, count(*) c from ai_usage group by 1) t),
    'bySentiment', (select coalesce(jsonb_object_agg(sentiment, c), '{}'::jsonb)
                    from (select coalesce(sentiment,'neutral') as sentiment, count(*) c from ai_usage group by 1) t),
    'segments', (
      select coalesce(jsonb_agg(seg order by (seg->>'interactions')::int desc), '[]'::jsonb)
      from (
        select jsonb_build_object(
          'userId', u.user_id, 'email', au.email, 'interactions', u.interactions,
          'topIntent', u.top_intent, 'avgSentiment', u.avg_sentiment, 'lastSeen', u.last_seen) as seg
        from (
          select user_id, count(*) as interactions,
                 mode() within group (order by intent) as top_intent,
                 round(avg(sentiment_score)::numeric, 2) as avg_sentiment,
                 max(ts) as last_seen
          from ai_usage where user_id is not null
          group by user_id order by count(*) desc limit 200
        ) u
        left join auth.users au on au.id = u.user_id
      ) s)
  ) into result;
  return result;
end; $$;

-- ── 6. TRIGGERS ─────────────────────────────────────────────────
-- touch_<table> triggers maintain updated_at on UPDATE. Two
-- near-identical helper functions (set_updated_at, touch_updated_at)
-- exist in prod and are used by different tables — captured as-is.

drop trigger if exists touch_profiles                on profiles;
drop trigger if exists touch_households              on households;
drop trigger if exists on_household_created          on households;
drop trigger if exists touch_transactions            on transactions;
drop trigger if exists touch_budgets                 on budgets;
drop trigger if exists touch_goals                   on goals;
drop trigger if exists touch_debts                   on debts;
drop trigger if exists touch_assets                  on assets;
drop trigger if exists cc_touch                      on category_classifications;
drop trigger if exists content_items_touch           on content_items;
drop trigger if exists subscriptions_touch           on subscriptions;

create trigger touch_profiles      before update on profiles      for each row execute function set_updated_at();
create trigger touch_households    before update on households    for each row execute function set_updated_at();
create trigger on_household_created after insert on households    for each row execute function handle_new_household();
create trigger touch_transactions  before update on transactions  for each row execute function set_updated_at();
create trigger touch_budgets       before update on budgets       for each row execute function set_updated_at();
create trigger touch_goals         before update on goals         for each row execute function set_updated_at();
create trigger touch_debts         before update on debts         for each row execute function set_updated_at();
create trigger touch_assets        before update on assets        for each row execute function set_updated_at();
create trigger cc_touch            before update on category_classifications for each row execute function set_updated_at();
create trigger content_items_touch before update on content_items for each row execute function touch_updated_at();
create trigger subscriptions_touch before update on subscriptions for each row execute function touch_updated_at();

-- Trigger on auth.users (Supabase pattern; lives on the auth schema
-- but references our public.handle_new_user). Safe under
-- `create or replace`-equivalent because we drop-if-exists first.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function handle_new_user();

-- ── 7. ROW-LEVEL SECURITY ───────────────────────────────────────

alter table profiles                  enable row level security;
alter table households                enable row level security;
alter table memberships               enable row level security;
alter table invitations               enable row level security;
alter table transactions              enable row level security;
alter table budgets                   enable row level security;
alter table goals                     enable row level security;
alter table debts                     enable row level security;
alter table assets                    enable row level security;
alter table exchange_rates            enable row level security;
alter table activity_log              enable row level security;
alter table admin_roles               enable row level security;
alter table content_items             enable row level security;
alter table content_favorites         enable row level security;
alter table subscriptions             enable row level security;
alter table category_classifications  enable row level security;
alter table ai_usage                  enable row level security;

-- activity_log
drop policy if exists "admins read all activity" on activity_log;
drop policy if exists "log_read"                 on activity_log;
create policy "admins read all activity" on activity_log for select using (is_admin('roles'));
create policy "log_read" on activity_log for select using (
  exists (select 1 from memberships where household_id = activity_log.household_id and user_id = auth.uid()));

-- admin_roles
drop policy if exists "self read admin_roles" on admin_roles;
create policy "self read admin_roles" on admin_roles for select using (user_id = auth.uid());

-- ai_usage
drop policy if exists "ai_usage_insert" on ai_usage;
drop policy if exists "ai_usage_select" on ai_usage;
create policy "ai_usage_insert" on ai_usage for insert to authenticated
  with check (is_member(household_id) and user_id = auth.uid());
create policy "ai_usage_select" on ai_usage for select to authenticated
  using (is_member(household_id) or is_admin('content'));

-- assets
drop policy if exists "admins read all assets" on assets;
drop policy if exists "assets_delete"          on assets;
drop policy if exists "assets_insert"          on assets;
drop policy if exists "assets_read"            on assets;
drop policy if exists "assets_update"          on assets;
create policy "admins read all assets" on assets for select using (is_admin('roles'));
create policy "assets_delete" on assets for delete using (role_in(household_id) in ('owner','admin','member'));
create policy "assets_insert" on assets for insert with check (role_in(household_id) in ('owner','admin','member'));
create policy "assets_read"   on assets for select using (
  exists (select 1 from memberships where household_id = assets.household_id and user_id = auth.uid()));
create policy "assets_update" on assets for update using (role_in(household_id) in ('owner','admin','member'));

-- budgets
drop policy if exists "admins read all budgets" on budgets;
drop policy if exists "budgets_delete"          on budgets;
drop policy if exists "budgets_insert"          on budgets;
drop policy if exists "budgets_read"            on budgets;
drop policy if exists "budgets_update"          on budgets;
create policy "admins read all budgets" on budgets for select using (is_admin('roles'));
create policy "budgets_delete" on budgets for delete using (role_in(household_id) in ('owner','admin','member'));
create policy "budgets_insert" on budgets for insert with check (role_in(household_id) in ('owner','admin','member'));
create policy "budgets_read"   on budgets for select using (
  exists (select 1 from memberships where household_id = budgets.household_id and user_id = auth.uid()));
create policy "budgets_update" on budgets for update using (role_in(household_id) in ('owner','admin','member'));

-- category_classifications
drop policy if exists "cc_admin_write" on category_classifications;
drop policy if exists "cc_read"        on category_classifications;
create policy "cc_admin_write" on category_classifications for all to authenticated
  using (is_admin('content')) with check (is_admin('content'));
create policy "cc_read" on category_classifications for select to authenticated using (true);

-- content_favorites
drop policy if exists "self favorites delete" on content_favorites;
drop policy if exists "self favorites insert" on content_favorites;
drop policy if exists "self favorites read"   on content_favorites;
create policy "self favorites delete" on content_favorites for delete using (user_id = auth.uid());
create policy "self favorites insert" on content_favorites for insert with check (user_id = auth.uid());
create policy "self favorites read"   on content_favorites for select using (user_id = auth.uid());

-- content_items
drop policy if exists "anyone reads published" on content_items;
drop policy if exists "content admin deletes"  on content_items;
drop policy if exists "content admin updates"  on content_items;
drop policy if exists "content admin writes"   on content_items;
create policy "anyone reads published" on content_items for select using (status = 'published' or is_admin('content'));
create policy "content admin deletes"  on content_items for delete using (is_admin('content'));
create policy "content admin updates"  on content_items for update using (is_admin('content'));
create policy "content admin writes"   on content_items for insert with check (is_admin('content'));

-- debts
drop policy if exists "admins read all debts" on debts;
drop policy if exists "debts_delete"          on debts;
drop policy if exists "debts_insert"          on debts;
drop policy if exists "debts_read"            on debts;
drop policy if exists "debts_update"          on debts;
create policy "admins read all debts" on debts for select using (is_admin('roles'));
create policy "debts_delete" on debts for delete using (role_in(household_id) in ('owner','admin','member'));
create policy "debts_insert" on debts for insert with check (role_in(household_id) in ('owner','admin','member'));
create policy "debts_read"   on debts for select using (
  exists (select 1 from memberships where household_id = debts.household_id and user_id = auth.uid()));
create policy "debts_update" on debts for update using (role_in(household_id) in ('owner','admin','member'));

-- exchange_rates
drop policy if exists "rates_read"  on exchange_rates;
drop policy if exists "rates_write" on exchange_rates;
create policy "rates_read" on exchange_rates for select using (
  exists (select 1 from memberships where household_id = exchange_rates.household_id and user_id = auth.uid()));
create policy "rates_write" on exchange_rates for all
  using (role_in(household_id) in ('owner','admin','member'))
  with check (role_in(household_id) in ('owner','admin','member'));

-- goals
drop policy if exists "admins read all goals" on goals;
drop policy if exists "goals_delete"          on goals;
drop policy if exists "goals_insert"          on goals;
drop policy if exists "goals_read"            on goals;
drop policy if exists "goals_update"          on goals;
create policy "admins read all goals" on goals for select using (is_admin('roles'));
create policy "goals_delete" on goals for delete using (role_in(household_id) in ('owner','admin','member'));
create policy "goals_insert" on goals for insert with check (role_in(household_id) in ('owner','admin','member'));
create policy "goals_read"   on goals for select using (
  exists (select 1 from memberships where household_id = goals.household_id and user_id = auth.uid()));
create policy "goals_update" on goals for update using (role_in(household_id) in ('owner','admin','member'));

-- households
drop policy if exists "admins read all households" on households;
drop policy if exists "anyone create household"    on households;
drop policy if exists "members read household"     on households;
drop policy if exists "owners delete household"    on households;
drop policy if exists "owners update household"    on households;
create policy "admins read all households" on households for select using (is_admin('roles'));
create policy "anyone create household"    on households for insert with check (created_by = auth.uid());
create policy "members read household"     on households for select using (is_member(id));
create policy "owners delete household"    on households for delete using (role_in(id) = 'owner');
create policy "owners update household"    on households for update using (role_in(id) = 'owner');

-- invitations
drop policy if exists "owners and admins read invitations"  on invitations;
drop policy if exists "owners and admins revoke invitations" on invitations;
drop policy if exists "owners and admins send invitations"   on invitations;
create policy "owners and admins read invitations"  on invitations for select using (role_in(household_id) in ('owner','admin'));
create policy "owners and admins revoke invitations" on invitations for delete using (role_in(household_id) in ('owner','admin'));
create policy "owners and admins send invitations"   on invitations for insert with check (
  role_in(household_id) in ('owner','admin') and invited_by = auth.uid());

-- memberships
drop policy if exists "admins read all memberships"                  on memberships;
drop policy if exists "members leave; owners remove non-owners"      on memberships;
drop policy if exists "members see other members"                    on memberships;
drop policy if exists "owners and admins add members"                on memberships;
drop policy if exists "owners change roles; admins change non-owners" on memberships;
create policy "admins read all memberships" on memberships for select using (is_admin('roles'));
create policy "members leave; owners remove non-owners" on memberships for delete using (
  user_id = auth.uid() or role_in(household_id) = 'owner' or (role_in(household_id) = 'admin' and role <> 'owner'));
create policy "members see other members" on memberships for select using (is_member(household_id));
create policy "owners and admins add members" on memberships for insert with check (
  role_in(household_id) in ('owner','admin'));
create policy "owners change roles; admins change non-owners" on memberships for update using (
  role_in(household_id) = 'owner' or (role_in(household_id) = 'admin' and role <> 'owner'));

-- profiles
drop policy if exists "admins read all profiles"     on profiles;
drop policy if exists "users read own profile"       on profiles;
drop policy if exists "users read profiles of co-members" on profiles;
drop policy if exists "users update own profile"     on profiles;
create policy "admins read all profiles" on profiles for select using (is_admin('roles'));
create policy "users read own profile"   on profiles for select using (id = auth.uid());
create policy "users read profiles of co-members" on profiles for select using (
  id in (select m2.user_id from memberships m1 join memberships m2 on m1.household_id = m2.household_id where m1.user_id = auth.uid()));
create policy "users update own profile" on profiles for update using (id = auth.uid());

-- subscriptions
drop policy if exists "self read subscriptions" on subscriptions;
create policy "self read subscriptions" on subscriptions for select using (user_id = auth.uid() or is_admin('roles'));

-- transactions
drop policy if exists "admins read all transactions" on transactions;
drop policy if exists "transactions_delete"          on transactions;
drop policy if exists "transactions_insert"          on transactions;
drop policy if exists "transactions_read"            on transactions;
drop policy if exists "transactions_update"          on transactions;
create policy "admins read all transactions" on transactions for select using (is_admin('roles'));
create policy "transactions_delete" on transactions for delete using (
  role_in(household_id) in ('owner','admin','member')
  or (role_in(household_id) = 'child' and created_by = auth.uid()));
create policy "transactions_insert" on transactions for insert with check (
  role_in(household_id) in ('owner','admin','member','child'));
create policy "transactions_read" on transactions for select using (
  exists (select 1 from memberships where household_id = transactions.household_id and user_id = auth.uid()));
create policy "transactions_update" on transactions for update using (
  role_in(household_id) in ('owner','admin','member')
  or (role_in(household_id) = 'child' and created_by = auth.uid()));

-- ── 8. FUNCTION GRANTS ──────────────────────────────────────────
-- Captured from production. Most app functions are granted to
-- authenticated; admin helpers also granted to anon (so the signed-out
-- error message can fire correctly inside is_admin's body).

grant execute on function public.accept_invitation(text)             to authenticated, anon, service_role;
grant execute on function public.accept_invitation(uuid)             to authenticated, anon, service_role;
grant execute on function public.admin_ai_usage_summary()            to authenticated, anon, service_role;
grant execute on function public.admin_dashboard_kpis()              to authenticated, anon, service_role;
grant execute on function public.admin_list_users()                  to authenticated, anon, service_role;
grant execute on function public.admin_weekly_trend(integer)         to authenticated, anon, service_role;
grant execute on function public.handle_new_household()              to service_role;
grant execute on function public.handle_new_user()                   to service_role;
grant execute on function public.is_admin(text)                      to authenticated, anon, service_role;
grant execute on function public.is_member(uuid)                     to authenticated, service_role;
grant execute on function public.leave_household(uuid)               to authenticated, anon, service_role;
grant execute on function public.role_in(uuid)                       to authenticated, service_role;
grant execute on function public.set_updated_at()                    to authenticated, anon, service_role;
grant execute on function public.touch_updated_at()                  to authenticated, anon, service_role;
grant execute on function public.transfer_ownership(uuid, uuid)      to authenticated, anon, service_role;

COMMIT;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260430091553_finflow_v4_1_initial_schema.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260430091553_finflow_v4_1_initial_schema
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260430091805_finflow_v4_1_rls_and_rpcs.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260430091805_finflow_v4_1_rls_and_rpcs
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260430092019_finflow_v4_1_security_hardening.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260430092019_finflow_v4_1_security_hardening
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260430092130_finflow_v4_1_revoke_public_execute.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260430092130_finflow_v4_1_revoke_public_execute
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260509182543_fix_households_rls_and_rpcs_v2.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260509182543_fix_households_rls_and_rpcs_v2
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260509185002_auto_create_household_on_signup.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260509185002_auto_create_household_on_signup
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260509190651_fix_rls_recursion_via_security_definer_helpers.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260509190651_fix_rls_recursion_via_security_definer_helpers
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260509190713_grant_execute_on_rls_helpers.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260509190713_grant_execute_on_rls_helpers
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260509231217_content_items_and_user_favorites.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260509231217_content_items_and_user_favorites
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260509234110_admin_data_layer.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260509234110_admin_data_layer
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260522025804_v646_category_classifications.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260522025804_v646_category_classifications
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260522025815_v646_ai_usage.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260522025815_v646_ai_usage
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260522025837_v646_admin_ai_usage_summary.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-20 stub: 20260522025837_v646_admin_ai_usage_summary
--
-- Applied via Supabase Dashboard pre-PR-#16; cumulative effect is
-- captured in 00000000000001_production_state_baseline.sql.
-- This stub exists so 'supabase db push' sees the local migration
-- directory and the remote schema_migrations tracker in 1:1 sync.
-- DO NOT add SQL here — it would re-run against fresh dev DBs.
select 1;
