-- ════════════════════════════════════════════════════════════════
-- FinFlow · Postgres schema (GENERATED — do not edit by hand)
--
-- Source of truth: supabase/migrations/*.sql
-- Regenerated by:  node scripts/db-migrations-check.mjs --fix
-- CI gate:         scripts/automation-run.mjs · "db-migrations"
--
-- To change the schema:
--   1. Add an additive migration at supabase/migrations/<timestamp>_<name>.sql
--   2. Run `node scripts/db-migrations-check.mjs --fix` to refresh this file
--   3. Apply the migration to staging (e.g. via the Supabase MCP
--      `apply_migration` tool) and the security advisor, per
--      docs/TEST_GOVERNANCE.md §4
-- ════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/00000000000000_initial_schema.sql
-- ─────────────────────────────────────────────────────────────────────
-- ════════════════════════════════════════════════════════════════
-- FinFlow · Cloud schema for Supabase (Postgres 15+)
-- Run this in: Supabase Dashboard → SQL Editor → New query
-- ════════════════════════════════════════════════════════════════

-- ── EXTENSIONS ────────────────────────────────────────────────
create extension if not exists pgcrypto;     -- gen_random_uuid()
create extension if not exists pg_trgm;      -- search

-- ════════════════════════════════════════════════════════════════
-- 1. PROFILES (extends auth.users)
-- ════════════════════════════════════════════════════════════════
create table if not exists profiles (
  id                uuid primary key references auth.users(id) on delete cascade,
  display_name      text,
  avatar_url        text,
  default_currency  text not null default 'USD',
  language          text not null default 'en',
  date_format       text not null default 'us',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- Auto-create profile on user signup
create or replace function handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1)));
  return new;
end;$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ════════════════════════════════════════════════════════════════
-- 2. HOUSEHOLDS (workspaces — family / business / personal)
-- ════════════════════════════════════════════════════════════════
create table if not exists households (
  id                uuid primary key default gen_random_uuid(),
  name              text not null,
  type              text not null check (type in ('family','business','personal','shared')),
  base_currency     text not null default 'USD',
  language          text default 'en',
  payoff_strategy   text default 'avalanche' check (payoff_strategy in ('avalanche','snowball')),
  extra_payment     numeric(15,2) default 0,
  created_by        uuid not null references auth.users(id),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists households_created_by_idx on households(created_by);

-- ════════════════════════════════════════════════════════════════
-- 3. MEMBERSHIPS (user × household, with role)
-- ════════════════════════════════════════════════════════════════
create table if not exists memberships (
  id                uuid primary key default gen_random_uuid(),
  household_id      uuid not null references households(id) on delete cascade,
  user_id           uuid references auth.users(id) on delete cascade,  -- NULL for non-authed members (e.g. children)
  role              text not null check (role in ('owner','admin','member','viewer','child')),
  display_name      text not null,
  household_role    text check (household_role in ('primary','partner','child','elder')),
  joined_at         timestamptz not null default now(),
  unique (household_id, user_id)
);
create index if not exists memberships_household_idx on memberships(household_id);
create index if not exists memberships_user_idx on memberships(user_id);

-- Auto-create owner membership when a household is created
create or replace function handle_new_household()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into memberships (household_id, user_id, role, display_name, household_role)
  values (
    new.id, new.created_by, 'owner',
    coalesce((select display_name from profiles where id = new.created_by), 'Owner'),
    'primary'
  );
  return new;
end;$$;

drop trigger if exists on_household_created on households;
create trigger on_household_created
  after insert on households
  for each row execute function handle_new_household();

-- ════════════════════════════════════════════════════════════════
-- 4. INVITATIONS
-- ════════════════════════════════════════════════════════════════
create table if not exists invitations (
  id                uuid primary key default gen_random_uuid(),
  household_id      uuid not null references households(id) on delete cascade,
  invited_email     text not null,
  invited_by        uuid not null references auth.users(id),
  role              text not null check (role in ('admin','member','viewer','child')),
  household_role    text,
  token             text not null unique default encode(gen_random_bytes(24), 'base64url'),
  expires_at        timestamptz not null default (now() + interval '14 days'),
  accepted_at       timestamptz,
  created_at        timestamptz not null default now()
);
create index if not exists invitations_token_idx on invitations(token) where accepted_at is null;
create index if not exists invitations_email_idx on invitations(invited_email) where accepted_at is null;

-- ════════════════════════════════════════════════════════════════
-- 5. DOMAIN TABLES (all scoped to household_id)
-- ════════════════════════════════════════════════════════════════

-- TRANSACTIONS
create table if not exists transactions (
  id                uuid primary key default gen_random_uuid(),
  household_id      uuid not null references households(id) on delete cascade,
  created_by        uuid references auth.users(id),
  member_id         uuid references memberships(id) on delete set null,
  type              text not null check (type in ('income','expense','investment','transfer')),
  amount            numeric(15,2) not null check (amount > 0),
  currency          text not null default 'USD',
  date              date not null,
  description       text not null,
  category          text not null,
  note              text,
  recurring         text check (recurring in ('','weekly','monthly','yearly')),
  attachment_url    text,
  extras            jsonb,                     -- v5+ extensions (paymentMethod, excluded, split, …)
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz   -- soft delete for sync
);
create index if not exists txns_household_date_idx on transactions(household_id, date desc) where deleted_at is null;
create index if not exists txns_household_member_idx on transactions(household_id, member_id) where deleted_at is null;
create index if not exists txns_household_cat_idx on transactions(household_id, category) where deleted_at is null;
create index if not exists txns_updated_idx on transactions(household_id, updated_at);

-- BUDGETS
create table if not exists budgets (
  id                uuid primary key default gen_random_uuid(),
  household_id      uuid not null references households(id) on delete cascade,
  category          text not null,
  monthly_limit     numeric(15,2) not null check (monthly_limit > 0),
  currency          text not null default 'USD',
  color             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  unique (household_id, category) where deleted_at is null
);

-- GOALS
create table if not exists goals (
  id                uuid primary key default gen_random_uuid(),
  household_id      uuid not null references households(id) on delete cascade,
  type              text not null check (type in ('emergency','savings','debt','investment','purchase','custom')),
  name              text not null,
  target_amount     numeric(15,2) not null check (target_amount > 0),
  current_amount    numeric(15,2) not null default 0,
  currency          text not null default 'USD',
  deadline          date,
  completed         boolean not null default false,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz
);

-- DEBTS
create table if not exists debts (
  id                uuid primary key default gen_random_uuid(),
  household_id      uuid not null references households(id) on delete cascade,
  type              text not null,
  name              text not null,
  lender            text,
  account_last4     text check (length(account_last4) <= 4),
  principal         numeric(15,2),
  current_balance   numeric(15,2) not null check (current_balance >= 0),
  interest_rate     numeric(6,3) not null check (interest_rate >= 0 and interest_rate < 100),
  minimum_payment   numeric(15,2) not null check (minimum_payment >= 0),
  due_date          date,
  currency          text not null default 'USD',
  extras            jsonb,                     -- tenureMonths, remainingMonths, paymentLog
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz
);

-- ASSETS
create table if not exists assets (
  id                uuid primary key default gen_random_uuid(),
  household_id      uuid not null references households(id) on delete cascade,
  type              text not null,
  name              text not null,
  value             numeric(15,2) not null check (value >= 0),
  currency          text not null default 'USD',
  liquidity         text not null check (liquidity in ('liquid','short','long')),
  note              text,
  last_updated      date,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz
);

-- EXCHANGE RATES (per-household — each can override defaults)
create table if not exists exchange_rates (
  household_id      uuid not null references households(id) on delete cascade,
  currency_code     text not null,
  rate_to_usd       numeric(15,6) not null check (rate_to_usd > 0),
  updated_at        timestamptz not null default now(),
  primary key (household_id, currency_code)
);

-- ACTIVITY LOG (audit trail for shared households)
create table if not exists activity_log (
  id                uuid primary key default gen_random_uuid(),
  household_id      uuid not null references households(id) on delete cascade,
  actor_id          uuid references auth.users(id),
  action            text not null check (action in ('created','updated','deleted','invited','accepted','removed','role_changed','transferred')),
  entity_type       text not null,
  entity_id         uuid,
  changes           jsonb,
  created_at        timestamptz not null default now()
);
create index if not exists activity_household_time_idx on activity_log(household_id, created_at desc);

-- ════════════════════════════════════════════════════════════════
-- 6. updated_at TRIGGERS
-- ════════════════════════════════════════════════════════════════
create or replace function set_updated_at()
returns trigger language plpgsql set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

do $$
declare t text;
begin
  for t in
    select unnest(array['profiles','households','transactions','budgets','goals','debts','assets'])
  loop
    execute format('drop trigger if exists touch_%I on %I', t, t);
    execute format('create trigger touch_%I before update on %I for each row execute function set_updated_at()', t, t);
  end loop;
end$$;

-- ════════════════════════════════════════════════════════════════
-- 7. ROW LEVEL SECURITY
-- ════════════════════════════════════════════════════════════════

-- Helper function: is the current user a member of this household?
create or replace function is_member(h_id uuid)
returns boolean language sql security definer stable set search_path = public as $$
  select exists (select 1 from memberships where household_id = h_id and user_id = auth.uid());
$$;

-- Helper: get current user's role in this household (null if not a member)
create or replace function role_in(h_id uuid)
returns text language sql security definer stable set search_path = public as $$
  select role from memberships where household_id = h_id and user_id = auth.uid() limit 1;
$$;

-- Enable RLS on every table
alter table profiles      enable row level security;
alter table households    enable row level security;
alter table memberships   enable row level security;
alter table invitations   enable row level security;
alter table transactions  enable row level security;
alter table budgets       enable row level security;
alter table goals         enable row level security;
alter table debts         enable row level security;
alter table assets        enable row level security;
alter table exchange_rates enable row level security;
alter table activity_log  enable row level security;

-- ── PROFILES ─────────────────────────────────────────────────
create policy "users read own profile"
  on profiles for select using (id = auth.uid());
create policy "users read profiles of co-members"
  on profiles for select using (
    id in (
      select m2.user_id from memberships m1
      join memberships m2 on m1.household_id = m2.household_id
      where m1.user_id = auth.uid()
    )
  );
create policy "users update own profile"
  on profiles for update using (id = auth.uid());

-- ── HOUSEHOLDS ───────────────────────────────────────────────
create policy "members read household"
  on households for select using (is_member(id));
create policy "anyone create household"
  on households for insert with check (created_by = auth.uid());
create policy "owners update household"
  on households for update using (role_in(id) = 'owner');
create policy "owners delete household"
  on households for delete using (role_in(id) = 'owner');

-- ── MEMBERSHIPS ──────────────────────────────────────────────
create policy "members see other members"
  on memberships for select using (is_member(household_id));
create policy "owners and admins add members"
  on memberships for insert with check (role_in(household_id) in ('owner','admin'));
create policy "owners change roles; admins change non-owners"
  on memberships for update using (
    role_in(household_id) = 'owner'
    or (role_in(household_id) = 'admin' and role != 'owner')
  );
create policy "members leave; owners remove non-owners"
  on memberships for delete using (
    user_id = auth.uid()                                  -- self-removal
    or role_in(household_id) = 'owner'                     -- owner removes anyone
    or (role_in(household_id) = 'admin' and role != 'owner') -- admin removes non-owners
  );

-- ── INVITATIONS ──────────────────────────────────────────────
create policy "owners and admins read invitations"
  on invitations for select using (role_in(household_id) in ('owner','admin'));
create policy "owners and admins send invitations"
  on invitations for insert with check (
    role_in(household_id) in ('owner','admin') and invited_by = auth.uid()
  );
create policy "owners and admins revoke invitations"
  on invitations for delete using (role_in(household_id) in ('owner','admin'));

-- ── TRANSACTIONS POLICIES (child can edit their own) ────────
-- Only transactions has a `created_by` column, so children's
-- "edit-your-own" rule applies only here.
create policy "transactions_read"   on transactions for select using (is_member(household_id));
create policy "transactions_insert" on transactions for insert with check (role_in(household_id) in ('owner','admin','member','child'));
create policy "transactions_update" on transactions for update using (
  role_in(household_id) in ('owner','admin','member')
  or (role_in(household_id) = 'child' and created_by = auth.uid())
);
create policy "transactions_delete" on transactions for delete using (
  role_in(household_id) in ('owner','admin','member')
  or (role_in(household_id) = 'child' and created_by = auth.uid())
);

-- ── BUDGETS / GOALS / DEBTS / ASSETS POLICIES (member-and-above) ─
-- These tables are managed at household-level, not per-user, so children
-- can read but not write.
do $$
declare tbl text;
begin
  foreach tbl in array array['budgets','goals','debts','assets'] loop
    execute format($p$create policy "%1$s_read"   on %1$s for select using (is_member(household_id))$p$, tbl);
    execute format($p$create policy "%1$s_insert" on %1$s for insert with check (role_in(household_id) in ('owner','admin','member'))$p$, tbl);
    execute format($p$create policy "%1$s_update" on %1$s for update using (role_in(household_id) in ('owner','admin','member'))$p$, tbl);
    execute format($p$create policy "%1$s_delete" on %1$s for delete using (role_in(household_id) in ('owner','admin','member'))$p$, tbl);
  end loop;
end$$;

-- ── EXCHANGE RATES ───────────────────────────────────────────
create policy "rates_read"   on exchange_rates for select using (is_member(household_id));
create policy "rates_write"  on exchange_rates for all    using (role_in(household_id) in ('owner','admin','member'));

-- ── ACTIVITY LOG ─────────────────────────────────────────────
create policy "log_read"   on activity_log for select using (is_member(household_id));
-- Inserts only via server-side functions (service_role) — no client policy needed

-- ════════════════════════════════════════════════════════════════
-- 8. HELPFUL VIEWS
-- ════════════════════════════════════════════════════════════════

-- A user's households with their role
-- security_invoker = true so RLS on underlying tables is enforced for the
-- querying user (not the view creator).
create or replace view my_households with (security_invoker = true) as
  select h.*, m.role, m.display_name as my_display_name, m.household_role
  from households h
  join memberships m on m.household_id = h.id
  where m.user_id = auth.uid();

-- Household summary (counts + totals) for the dashboard
create or replace view household_summary with (security_invoker = true) as
  select
    h.id as household_id,
    (select count(*) from memberships where household_id = h.id) as member_count,
    (select count(*) from transactions where household_id = h.id and deleted_at is null) as txn_count,
    (select count(*) from debts where household_id = h.id and deleted_at is null) as debt_count,
    (select coalesce(sum(current_balance), 0) from debts where household_id = h.id and deleted_at is null) as total_debt_native,
    (select count(*) from assets where household_id = h.id and deleted_at is null) as asset_count,
    (select coalesce(sum(value), 0) from assets where household_id = h.id and deleted_at is null) as total_assets_native
  from households h;

grant select on my_households, household_summary to authenticated;

-- ════════════════════════════════════════════════════════════════
-- 9. RPCs — invitation acceptance, ownership transfer, leave household
-- ════════════════════════════════════════════════════════════════

-- Accept an invitation by token. Caller must be authenticated.
-- Validates: token exists, not expired, not already accepted, email matches caller.
-- Atomically: creates membership, marks invitation accepted, writes audit entry.
create or replace function accept_invitation(invite_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inv record;
  caller_email text;
  new_membership_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Must be signed in to accept an invitation';
  end if;

  select email into caller_email from auth.users where id = auth.uid();
  select * into inv from invitations
    where token = invite_token and accepted_at is null
    limit 1;

  if inv is null then raise exception 'Invitation not found or already accepted'; end if;
  if inv.expires_at < now() then raise exception 'Invitation expired'; end if;
  if lower(inv.invited_email) <> lower(caller_email) then
    raise exception 'Invitation was sent to %, but you are signed in as %', inv.invited_email, caller_email;
  end if;
  -- Already a member?
  if exists (select 1 from memberships where household_id = inv.household_id and user_id = auth.uid()) then
    update invitations set accepted_at = now() where id = inv.id;
    return jsonb_build_object('household_id', inv.household_id, 'already_member', true);
  end if;

  insert into memberships (household_id, user_id, role, display_name, household_role)
  values (inv.household_id, auth.uid(), inv.role,
          coalesce((select display_name from profiles where id = auth.uid()),
                   split_part(caller_email, '@', 1)),
          inv.household_role)
  returning id into new_membership_id;

  update invitations set accepted_at = now() where id = inv.id;

  insert into activity_log (household_id, actor_id, action, entity_type, entity_id)
  values (inv.household_id, auth.uid(), 'accepted', 'invitation', inv.id);

  return jsonb_build_object(
    'household_id', inv.household_id,
    'membership_id', new_membership_id,
    'role', inv.role
  );
end;
$$;

grant execute on function accept_invitation(text) to authenticated;

-- Transfer ownership of a household. Only an existing owner may call.
-- Promotes target to owner, demotes caller to admin.
create or replace function transfer_ownership(h_id uuid, to_user uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_role text;
  target_membership uuid;
begin
  if auth.uid() is null then raise exception 'Must be signed in'; end if;

  select role into caller_role from memberships
    where household_id = h_id and user_id = auth.uid();
  if caller_role <> 'owner' then
    raise exception 'Only the owner can transfer ownership';
  end if;

  select id into target_membership from memberships
    where household_id = h_id and user_id = to_user;
  if target_membership is null then
    raise exception 'Target user is not a member of this household';
  end if;

  -- Atomic role swap
  update memberships set role = 'owner' where id = target_membership;
  update memberships set role = 'admin' where household_id = h_id and user_id = auth.uid();

  insert into activity_log (household_id, actor_id, action, entity_type, entity_id, changes)
  values (h_id, auth.uid(), 'transferred', 'membership', target_membership,
          jsonb_build_object('to_user', to_user));

  return true;
end;
$$;

grant execute on function transfer_ownership(uuid, uuid) to authenticated;

-- Leave a household. Owner cannot leave if they are the sole owner —
-- must transfer ownership first.
create or replace function leave_household(h_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  caller_role text;
  owner_count int;
begin
  if auth.uid() is null then raise exception 'Must be signed in'; end if;

  select role into caller_role from memberships
    where household_id = h_id and user_id = auth.uid();
  if caller_role is null then raise exception 'Not a member of this household'; end if;

  if caller_role = 'owner' then
    select count(*) into owner_count from memberships
      where household_id = h_id and role = 'owner';
    if owner_count <= 1 then
      raise exception 'Sole owner cannot leave — transfer ownership first or delete the household';
    end if;
  end if;

  delete from memberships where household_id = h_id and user_id = auth.uid();

  insert into activity_log (household_id, actor_id, action, entity_type)
  values (h_id, auth.uid(), 'removed', 'membership');

  return true;
end;
$$;

grant execute on function leave_household(uuid) to authenticated;

-- ════════════════════════════════════════════════════════════════
-- 10. Security hardening — revoke broad grants
-- ════════════════════════════════════════════════════════════════

-- Internal helpers (only invoked from within RLS policies / triggers).
-- Never callable as RPCs.
revoke execute on function handle_new_user()      from anon, authenticated, public;
revoke execute on function handle_new_household() from anon, authenticated, public;
revoke execute on function is_member(uuid)        from anon, authenticated, public;
revoke execute on function role_in(uuid)          from anon, authenticated, public;

-- Public-facing RPCs — explicitly limited to authenticated only.
revoke all on function accept_invitation(text)        from public;
revoke all on function transfer_ownership(uuid, uuid) from public;
revoke all on function leave_household(uuid)          from public;
grant execute on function accept_invitation(text)        to authenticated;
grant execute on function transfer_ownership(uuid, uuid) to authenticated;
grant execute on function leave_household(uuid)          to authenticated;

-- ════════════════════════════════════════════════════════════════
-- DONE.  Next step:
--   1. In Supabase: create an Edge Function for sending invite emails
--   2. In your app: drop in @supabase/supabase-js and start migrating
-- ════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260523060000_admin_roles_and_dashboard_kpis.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-04 — version-control the privileged admin surface.
--
-- Brings the admin authorisation layer + the dashboard KPIs RPC into a
-- reviewable, source-controlled migration. Both were previously hand-run
-- against production via the Supabase SQL editor and so were absent from
-- any committed schema, meaning a fresh environment provisioned from the
-- repo would silently lack the privilege model the admin app relies on.
--
-- Scope (deliberately narrow, matching the TD-04 spec verbatim):
--   • admin_role enum            ('super', 'roles', 'content')
--   • admin_roles table          (user_id ↔ role)
--   • is_admin() / has_admin_role() helper functions
--   • RLS on admin_roles
--   • admin_dashboard_kpis() RPC returning the DashboardKpis shape that
--     admin/src/lib/adminApi.ts already expects
--
-- Out of scope for this migration (filed as follow-up TD-04-extension):
--   • subscriptions      table  (referenced by admin/src/lib/adminApi.ts
--                                fetchAllSubscriptions) — KPI fields
--                                paidSubscriptions / mrr will read this
--                                once it's versioned; until then they
--                                report 0.
--   • content_items      table  (referenced by admin/src/lib/contentApi.ts
--                                + Insights consumer page). Same story
--                                for publishedArticles / contentFavorites.
--   • admin_weekly_trend / admin_ai_usage_summary / admin_list_users RPCs
--     (also unversioned today).
--
-- Each follow-up migration ratchets one more piece of the unversioned
-- admin surface into the committed schema and CAN replace this function
-- via CREATE OR REPLACE FUNCTION to plug in the real numbers.

-- ── 1. admin_role enum ───────────────────────────────────────────
-- Wrapped in a DO block so re-applying the migration after a partial
-- rollback doesn't fail. The enum mirrors the AdminRole TS type in
-- admin/src/types.ts so the wire contract stays single-sourced.
do $$
begin
  if not exists (select 1 from pg_type where typname = 'admin_role') then
    create type admin_role as enum ('super', 'roles', 'content');
  end if;
end$$;

-- ── 2. admin_roles table ─────────────────────────────────────────
-- One row per privileged user. user_id is the PK so a user is granted at
-- most one tier; promote/demote is a single UPDATE. References auth.users
-- (matching the existing profiles.id → auth.users.id pattern in the
-- baseline) so deleting a user cascades the privilege away.
create table if not exists admin_roles (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  role        admin_role not null,
  granted_by  uuid references auth.users(id),
  granted_at  timestamptz not null default now(),
  notes       text
);

create index if not exists admin_roles_role_idx on admin_roles(role);

-- ── 3. helper functions ──────────────────────────────────────────
-- Server-side checks. SECURITY DEFINER + a fixed search_path so callers
-- can use these from any RLS expression without the lookup itself going
-- through RLS (which would create a recursion: "to know if you're admin,
-- read admin_roles, which requires being admin to read"). is_member /
-- role_in in the baseline use the same pattern.
create or replace function is_admin(uid uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (select 1 from public.admin_roles where user_id = uid);
$$;

create or replace function has_admin_role(target_role admin_role, uid uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.admin_roles
    where user_id = uid
      and (role = target_role or role = 'super')   -- super implies all tiers
  );
$$;

-- ── 4. RLS on admin_roles ────────────────────────────────────────
-- Read rules:
--   • a user can see their own row (so the admin app's
--     fetchMyAdminRole(uid) works for any signed-in user)
--   • a super admin can see every row (for an "admins list" UI)
-- Write rules:
--   • only super admins can grant or revoke privilege
alter table admin_roles enable row level security;

drop policy if exists "user reads own admin row"    on admin_roles;
drop policy if exists "super reads all admin rows"  on admin_roles;
drop policy if exists "super inserts admin rows"    on admin_roles;
drop policy if exists "super updates admin rows"    on admin_roles;
drop policy if exists "super deletes admin rows"    on admin_roles;

create policy "user reads own admin row"
  on admin_roles for select using (user_id = auth.uid());

create policy "super reads all admin rows"
  on admin_roles for select using (has_admin_role('super'));

create policy "super inserts admin rows"
  on admin_roles for insert with check (has_admin_role('super'));

create policy "super updates admin rows"
  on admin_roles for update using (has_admin_role('super')) with check (has_admin_role('super'));

create policy "super deletes admin rows"
  on admin_roles for delete using (has_admin_role('super'));

-- ── 5. admin_dashboard_kpis() RPC ────────────────────────────────
-- Returns the DashboardKpis shape expected by
-- admin/src/lib/adminApi.ts:fetchDashboardKpis. The output is a single
-- jsonb object, matching the admin app's `.rpc('admin_dashboard_kpis')`
-- + `data as DashboardKpis` cast.
--
-- SECURITY DEFINER + search_path so a logged-in admin can read the
-- aggregates without each underlying table needing its RLS relaxed.
-- The function is GUARDED at the top: callers who are not in admin_roles
-- get a permission-denied error, never the data.
--
-- Fields whose backing tables are still unversioned today return 0;
-- each such line is commented with the table/migration that will
-- replace it.
create or replace function admin_dashboard_kpis()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null or not exists (select 1 from public.admin_roles where user_id = uid) then
    raise exception 'admin_dashboard_kpis: caller is not an admin'
      using errcode = '42501';   -- insufficient_privilege
  end if;

  return jsonb_build_object(
    -- Total users in the system. profiles is the authoritative public mirror
    -- of auth.users (every signup creates a row via handle_new_user()).
    'totalUsers',        (select count(*) from public.profiles),

    -- Households + multi-member ratio.
    'totalHouseholds',   (select count(*) from public.households),
    'multiMemberPct',    (
      select coalesce(
        round(100.0 * count(*) filter (where mc > 1) / nullif(count(*), 0), 1),
        0
      )
      from (
        select household_id, count(*) as mc
        from public.memberships
        group by household_id
      ) hh
    ),

    -- 7-day active windows. "Active" here means "appears as created_by on a
    -- non-deleted transaction in the last 7 days". A richer notion (logins,
    -- sessions) needs an events table, deferred.
    'activeUsers7d',     (
      select count(distinct created_by)
      from public.transactions
      where deleted_at is null
        and created_at >= now() - interval '7 days'
        and created_by is not null
    ),
    'activeHouseholds7d',(
      select count(distinct household_id)
      from public.transactions
      where deleted_at is null
        and created_at >= now() - interval '7 days'
    ),

    -- New signups in the last 7 / 30 days, from profiles.created_at.
    'signups7d',         (select count(*) from public.profiles where created_at >= now() - interval '7 days'),
    'signups30d',        (select count(*) from public.profiles where created_at >= now() - interval '30 days'),

    -- All-time + 7-day transaction counts (deleted excluded).
    'totalTransactions', (select count(*) from public.transactions where deleted_at is null),
    'transactions7d',    (
      select count(*) from public.transactions
      where deleted_at is null
        and created_at >= now() - interval '7 days'
    ),

    -- Content KPIs depend on the content_items table which is referenced
    -- by admin/src/lib/contentApi.ts but not yet in versioned migrations.
    -- TODO(TD-04-content): once content_items lands, replace these with:
    --   (select count(*) from public.content_items where status = 'published')
    --   (sum of favorites across content_items / a content_favorites join)
    'publishedArticles', 0,
    'contentFavorites',  0,

    -- Subscription KPIs depend on the subscriptions table (also
    -- referenced by admin/src/lib/adminApi.ts but unversioned today).
    -- TODO(TD-04-subscriptions): once subscriptions lands, replace with
    -- counts/sums filtered by status='active' AND tier != 'free'.
    'paidSubscriptions', 0,
    'mrr',               0,

    -- Server time the snapshot was computed.
    'computedAt',        now()
  );
end;
$$;

-- Authenticated users can CALL the function; the function body itself
-- enforces the admin check on uid. Without this grant, even an admin
-- can't invoke the RPC from the client.
grant execute on function admin_dashboard_kpis() to authenticated;
grant execute on function is_admin(uuid)         to authenticated;
grant execute on function has_admin_role(admin_role, uuid) to authenticated;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260524070000_budgets_add_period.sql
-- ─────────────────────────────────────────────────────────────────────
-- Add budget period fields so budgets are stored server-side (TD-13)
-- Adds: period (text), period_start (date), period_end (date)

BEGIN;

ALTER TABLE budgets
  ADD COLUMN period text NOT NULL DEFAULT 'monthly',
  ADD COLUMN period_start date NULL,
  ADD COLUMN period_end date NULL;

ALTER TABLE budgets
  ADD CONSTRAINT budgets_period_check CHECK (period IN ('monthly','quarterly','half_yearly','annual','custom'));

COMMIT;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260524071000_audit_triggers.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-08: Populate activity_log from domain CRUD (transactions, budgets, goals, debts, assets, memberships)
-- Creates a trigger function that inserts an activity_log row on INSERT/UPDATE/DELETE.
--
-- Review correction (lead): the originally-submitted patch was missing
-- two things: (a) the `memberships` table from the trigger list (the
-- prompt explicitly listed it; multi-household member changes are exactly
-- the audit signal we need), and (b) `SET search_path = public, pg_temp`
-- on the SECURITY DEFINER function — without this, a malicious schema
-- on the caller's search path can shadow `activity_log` / `auth.uid()`
-- and exfiltrate or tamper with the audit trail. Both fixed inline.

BEGIN;

-- Safety: replace the function if it exists
CREATE OR REPLACE FUNCTION public.log_domain_activity()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  h uuid;
  act text;
  ent text := TG_TABLE_NAME;
  ent_id uuid;
  ch jsonb;
BEGIN
  IF TG_OP = 'INSERT' THEN
    act := 'created';
    h := NEW.household_id;
    ent_id := NEW.id;
    ch := to_jsonb(NEW);
  ELSIF TG_OP = 'UPDATE' THEN
    act := 'updated';
    h := NEW.household_id;
    ent_id := NEW.id;
    ch := jsonb_build_object('old', to_jsonb(OLD), 'new', to_jsonb(NEW));
  ELSIF TG_OP = 'DELETE' THEN
    act := 'deleted';
    h := OLD.household_id;
    ent_id := OLD.id;
    ch := to_jsonb(OLD);
  ELSE
    RETURN NULL;
  END IF;

  INSERT INTO activity_log (household_id, actor_id, action, entity_type, entity_id, changes)
  VALUES (h, auth.uid(), act, ent, ent_id, ch);

  RETURN NULL;
END;
$$;

-- Attach triggers for domain tables
DO $$
BEGIN
  -- transactions
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'activity_txn_trigger') THEN
    CREATE TRIGGER activity_txn_trigger
      AFTER INSERT OR UPDATE OR DELETE ON transactions
      FOR EACH ROW EXECUTE FUNCTION public.log_domain_activity();
  END IF;
  -- budgets
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'activity_budgets_trigger') THEN
    CREATE TRIGGER activity_budgets_trigger
      AFTER INSERT OR UPDATE OR DELETE ON budgets
      FOR EACH ROW EXECUTE FUNCTION public.log_domain_activity();
  END IF;
  -- goals
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'activity_goals_trigger') THEN
    CREATE TRIGGER activity_goals_trigger
      AFTER INSERT OR UPDATE OR DELETE ON goals
      FOR EACH ROW EXECUTE FUNCTION public.log_domain_activity();
  END IF;
  -- debts
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'activity_debts_trigger') THEN
    CREATE TRIGGER activity_debts_trigger
      AFTER INSERT OR UPDATE OR DELETE ON debts
      FOR EACH ROW EXECUTE FUNCTION public.log_domain_activity();
  END IF;
  -- assets
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'activity_assets_trigger') THEN
    CREATE TRIGGER activity_assets_trigger
      AFTER INSERT OR UPDATE OR DELETE ON assets
      FOR EACH ROW EXECUTE FUNCTION public.log_domain_activity();
  END IF;
  -- memberships (review-correction: was missing in submitted patch)
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'activity_memberships_trigger') THEN
    CREATE TRIGGER activity_memberships_trigger
      AFTER INSERT OR UPDATE OR DELETE ON memberships
      FOR EACH ROW EXECUTE FUNCTION public.log_domain_activity();
  END IF;
END$$;

COMMIT;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260524073000_replace_all_rpc.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-09: Atomic replace RPCs for bulk imports
-- Adds `replace_<entity>(h uuid, rows jsonb)` functions that soft-delete
-- existing rows for a household and insert the provided rows inside a
-- single transaction, returning the inserted rows.

BEGIN;

-- TRANSACTIONS
CREATE OR REPLACE FUNCTION public.replace_transactions(h uuid, rows jsonb)
RETURNS SETOF transactions
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Must be signed in'; END IF;
  IF NOT is_member(h) THEN RAISE EXCEPTION 'Not a member of this household'; END IF;

  -- soft-delete existing
  UPDATE transactions SET deleted_at = now() WHERE household_id = h AND deleted_at IS NULL;

  -- insert new rows
  RETURN QUERY
  INSERT INTO transactions (id, household_id, created_by, member_id, type, amount, currency, date, description, category, note, recurring, attachment_url, extras, created_at, updated_at, deleted_at)
  SELECT t.id::uuid, h, t.created_by::uuid, t.member_id::uuid, t.type, t.amount::numeric, t.currency, t.date::date, t.description, t.category, t.note, t.recurring, t.attachment_url, t.extras::jsonb, t.created_at::timestamptz, t.updated_at::timestamptz, t.deleted_at::timestamptz
  FROM jsonb_populate_recordset(NULL::transactions, rows) as t;
END;
$$;
GRANT EXECUTE ON FUNCTION public.replace_transactions(uuid, jsonb) TO authenticated;

-- BUDGETS
CREATE OR REPLACE FUNCTION public.replace_budgets(h uuid, rows jsonb)
RETURNS SETOF budgets
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Must be signed in'; END IF;
  IF NOT is_member(h) THEN RAISE EXCEPTION 'Not a member of this household'; END IF;

  UPDATE budgets SET deleted_at = now() WHERE household_id = h AND deleted_at IS NULL;

  RETURN QUERY
  INSERT INTO budgets (id, household_id, category, monthly_limit, currency, color, period, period_start, period_end, created_at, updated_at, deleted_at)
  SELECT t.id::uuid, h, t.category, t.monthly_limit::numeric, t.currency, t.color, t.period, t.period_start::date, t.period_end::date, t.created_at::timestamptz, t.updated_at::timestamptz, t.deleted_at::timestamptz
  FROM jsonb_populate_recordset(NULL::budgets, rows) as t;
END;
$$;
GRANT EXECUTE ON FUNCTION public.replace_budgets(uuid, jsonb) TO authenticated;

-- GOALS
CREATE OR REPLACE FUNCTION public.replace_goals(h uuid, rows jsonb)
RETURNS SETOF goals
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Must be signed in'; END IF;
  IF NOT is_member(h) THEN RAISE EXCEPTION 'Not a member of this household'; END IF;

  UPDATE goals SET deleted_at = now() WHERE household_id = h AND deleted_at IS NULL;

  RETURN QUERY
  INSERT INTO goals (id, household_id, type, name, target_amount, current_amount, currency, deadline, completed, created_at, updated_at, deleted_at)
  SELECT t.id::uuid, h, t.type, t.name, t.target_amount::numeric, t.current_amount::numeric, t.currency, t.deadline::date, t.completed::boolean, t.created_at::timestamptz, t.updated_at::timestamptz, t.deleted_at::timestamptz
  FROM jsonb_populate_recordset(NULL::goals, rows) as t;
END;
$$;
GRANT EXECUTE ON FUNCTION public.replace_goals(uuid, jsonb) TO authenticated;

-- DEBTS
CREATE OR REPLACE FUNCTION public.replace_debts(h uuid, rows jsonb)
RETURNS SETOF debts
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Must be signed in'; END IF;
  IF NOT is_member(h) THEN RAISE EXCEPTION 'Not a member of this household'; END IF;

  UPDATE debts SET deleted_at = now() WHERE household_id = h AND deleted_at IS NULL;

  RETURN QUERY
  INSERT INTO debts (id, household_id, type, name, lender, account_last4, principal, current_balance, interest_rate, minimum_payment, due_date, currency, extras, created_at, updated_at, deleted_at)
  SELECT t.id::uuid, h, t.type, t.name, t.lender, t.account_last4, t.principal::numeric, t.current_balance::numeric, t.interest_rate::numeric, t.minimum_payment::numeric, t.due_date::date, t.currency, t.extras::jsonb, t.created_at::timestamptz, t.updated_at::timestamptz, t.deleted_at::timestamptz
  FROM jsonb_populate_recordset(NULL::debts, rows) as t;
END;
$$;
GRANT EXECUTE ON FUNCTION public.replace_debts(uuid, jsonb) TO authenticated;

-- ASSETS
CREATE OR REPLACE FUNCTION public.replace_assets(h uuid, rows jsonb)
RETURNS SETOF assets
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Must be signed in'; END IF;
  IF NOT is_member(h) THEN RAISE EXCEPTION 'Not a member of this household'; END IF;

  UPDATE assets SET deleted_at = now() WHERE household_id = h AND deleted_at IS NULL;

  RETURN QUERY
  INSERT INTO assets (id, household_id, type, name, value, currency, liquidity, note, last_updated, created_at, updated_at, deleted_at)
  SELECT t.id::uuid, h, t.type, t.name, t.value::numeric, t.currency, t.liquidity, t.note, t.last_updated::date, t.created_at::timestamptz, t.updated_at::timestamptz, t.deleted_at::timestamptz
  FROM jsonb_populate_recordset(NULL::assets, rows) as t;
END;
$$;
GRANT EXECUTE ON FUNCTION public.replace_assets(uuid, jsonb) TO authenticated;

-- MEMBERSHIPS (members)
CREATE OR REPLACE FUNCTION public.replace_memberships(h uuid, rows jsonb)
RETURNS SETOF memberships
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Must be signed in'; END IF;
  IF NOT is_member(h) THEN RAISE EXCEPTION 'Not a member of this household'; END IF;

  DELETE FROM memberships WHERE household_id = h;

  RETURN QUERY
  INSERT INTO memberships (id, household_id, user_id, role, display_name, household_role, joined_at)
  SELECT t.id::uuid, h, t.user_id::uuid, t.role, t.display_name, t.household_role, t.joined_at::timestamptz
  FROM jsonb_populate_recordset(NULL::memberships, rows) as t;
END;
$$;
GRANT EXECUTE ON FUNCTION public.replace_memberships(uuid, jsonb) TO authenticated;

COMMIT;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260524075000_subscriptions_table_and_kpis.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-04-ext-a: Subscriptions table + admin KPI wiring
-- Adds `subscriptions` table used by admin UI and the `paidSubscriptions`/`mrr` KPI.

BEGIN;

-- 1) Subscriptions table
create table if not exists subscriptions (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid references auth.users(id) on delete cascade,
  household_id      uuid references households(id) on delete set null,
  tier              text not null check (tier in ('free','family','premium','enterprise')),
  status            text not null check (status in ('active','past_due','canceled','trialing')),
  monthly_amount    numeric(15,2) not null default 0,
  currency          text not null default 'USD',
  stripe_subscription_id text,
  started_at        timestamptz not null default now(),
  renews_at         timestamptz,
  failure_count     integer not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz
);
create index if not exists subscriptions_user_idx on subscriptions(user_id);
create index if not exists subscriptions_household_idx on subscriptions(household_id);
create index if not exists subscriptions_status_idx on subscriptions(status);

-- 2) touch_updated trigger for subscriptions
-- reuse the generic set_updated_at() trigger function defined in schema.sql
drop trigger if exists touch_subscriptions on subscriptions;
create trigger touch_subscriptions before update on subscriptions for each row execute function set_updated_at();

-- 3) Row-level security and policies
alter table subscriptions enable row level security;

drop policy if exists "subscriptions_read" on subscriptions;
drop policy if exists "subscriptions_insert" on subscriptions;
drop policy if exists "subscriptions_update" on subscriptions;
drop policy if exists "subscriptions_delete" on subscriptions;

create policy "subscriptions_read" on subscriptions for select using (
  user_id = auth.uid() or is_admin()
);
create policy "subscriptions_insert" on subscriptions for insert with check (
  (user_id = auth.uid()) or is_admin()
);
create policy "subscriptions_update" on subscriptions for update using (
  (user_id = auth.uid()) or is_admin()
) with check (
  (user_id = auth.uid()) or is_admin()
);
create policy "subscriptions_delete" on subscriptions for delete using (
  is_admin()
);

-- 4) Audit trigger: log domain activity for subscriptions
-- If the audit trigger function exists (TD-08), attach it; otherwise skip.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'log_domain_activity') THEN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'activity_subscriptions_trigger') THEN
      CREATE TRIGGER activity_subscriptions_trigger
        AFTER INSERT OR UPDATE OR DELETE ON subscriptions
        FOR EACH ROW EXECUTE FUNCTION public.log_domain_activity();
    END IF;
  END IF;
END$$;

-- 5) Update admin_dashboard_kpis() to include subscription counts and MRR
-- Create-or-replace the function so environments can be migrated in a single
-- replayable migration.
create or replace function admin_dashboard_kpis()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null or not exists (select 1 from public.admin_roles where user_id = uid) then
    raise exception 'admin_dashboard_kpis: caller is not an admin'
      using errcode = '42501';   -- insufficient_privilege
  end if;

  return jsonb_build_object(
    'totalUsers',        (select count(*) from public.profiles),
    'totalHouseholds',   (select count(*) from public.households),
    'multiMemberPct',    (
      select coalesce(
        round(100.0 * count(*) filter (where mc > 1) / nullif(count(*), 0), 1),
        0
      )
      from (
        select household_id, count(*) as mc
        from public.memberships
        group by household_id
      ) hh
    ),
    'activeUsers7d',     (
      select count(distinct created_by)
      from public.transactions
      where deleted_at is null
        and created_at >= now() - interval '7 days'
        and created_by is not null
    ),
    'activeHouseholds7d',(
      select count(distinct household_id)
      from public.transactions
      where deleted_at is null
        and created_at >= now() - interval '7 days'
    ),

    'signups7d',         (select count(*) from public.profiles where created_at >= now() - interval '7 days'),
    'signups30d',        (select count(*) from public.profiles where created_at >= now() - interval '30 days'),

    'totalTransactions', (select count(*) from public.transactions where deleted_at is null),
    'transactions7d',    (
      select count(*) from public.transactions
      where deleted_at is null
        and created_at >= now() - interval '7 days'
    ),

    'publishedArticles', 0,
    'contentFavorites',  0,

    -- Subscriptions KPIs (now backed by public.subscriptions)
    'paidSubscriptions', (
      select count(*) from public.subscriptions
      where deleted_at is null
        and status = 'active'
        and tier <> 'free'
    ),
    'mrr', (
      select coalesce(sum(monthly_amount), 0) from public.subscriptions
      where deleted_at is null
        and status = 'active'
        and tier <> 'free'
    ),

    'computedAt',        now()
  );
end;
$$;

-- Ensure the function is callable by authenticated users (the function itself
-- enforces admin privileges inside its body).
grant execute on function admin_dashboard_kpis() to authenticated;

COMMIT;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260524076000_content_items_table_and_kpis.sql
-- ─────────────────────────────────────────────────────────────────────
-- TD-04-ext-b: Content items + favorites tables + admin KPI wiring
-- Adds `content_items` and `content_favorites` for the help/content module,
-- enables RLS, attaches audit triggers (if present), and updates
-- `admin_dashboard_kpis()` to compute `publishedArticles` and `contentFavorites`.

BEGIN;

-- 1) Content items
create table if not exists content_items (
  id uuid primary key default gen_random_uuid(),
  author_id uuid references auth.users(id) on delete set null,
  title text not null,
  slug text not null,
  body text,
  status text not null check (status in ('draft','published','archived')) default 'draft',
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create unique index if not exists content_items_slug_idx on content_items(slug);
create index if not exists content_items_status_idx on content_items(status);
create index if not exists content_items_author_idx on content_items(author_id);

-- 2) Content favorites (user -> content)
create table if not exists content_favorites (
  id uuid primary key default gen_random_uuid(),
  content_id uuid references content_items(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint content_favorites_unique unique (content_id, user_id)
);
create index if not exists content_favorites_user_idx on content_favorites(user_id);
create index if not exists content_favorites_content_idx on content_favorites(content_id);

-- 3) touch_updated triggers
drop trigger if exists touch_content_items on content_items;
create trigger touch_content_items before update on content_items for each row execute function set_updated_at();

drop trigger if exists touch_content_favorites on content_favorites;
create trigger touch_content_favorites before update on content_favorites for each row execute function set_updated_at();

-- 4) Row level security and policies
alter table content_items enable row level security;
alter table content_favorites enable row level security;

-- content_items policies
drop policy if exists "content_items_read" on content_items;
drop policy if exists "content_items_insert" on content_items;
drop policy if exists "content_items_update" on content_items;
drop policy if exists "content_items_delete" on content_items;

create policy "content_items_read" on content_items for select using (
  status = 'published' or author_id = auth.uid() or is_admin()
);
create policy "content_items_insert" on content_items for insert with check (
  (author_id = auth.uid()) or is_admin()
);
create policy "content_items_update" on content_items for update using (
  (author_id = auth.uid()) or is_admin()
) with check (
  (author_id = auth.uid()) or is_admin()
);
create policy "content_items_delete" on content_items for delete using (
  is_admin()
);

-- content_favorites policies
drop policy if exists "content_favorites_read" on content_favorites;
drop policy if exists "content_favorites_insert" on content_favorites;
drop policy if exists "content_favorites_delete" on content_favorites;

create policy "content_favorites_read" on content_favorites for select using (
  user_id = auth.uid() or is_admin()
);
create policy "content_favorites_insert" on content_favorites for insert with check (
  user_id = auth.uid() or is_admin()
);
create policy "content_favorites_delete" on content_favorites for delete using (
  user_id = auth.uid() or is_admin()
);

-- 5) Audit triggers: attach if `log_domain_activity()` exists
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'log_domain_activity') THEN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'activity_content_items_trigger') THEN
      CREATE TRIGGER activity_content_items_trigger
        AFTER INSERT OR UPDATE OR DELETE ON content_items
        FOR EACH ROW EXECUTE FUNCTION public.log_domain_activity();
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'activity_content_favorites_trigger') THEN
      CREATE TRIGGER activity_content_favorites_trigger
        AFTER INSERT OR UPDATE OR DELETE ON content_favorites
        FOR EACH ROW EXECUTE FUNCTION public.log_domain_activity();
    END IF;
  END IF;
END$$;

-- 6) Update admin_dashboard_kpis() to include content metrics
create or replace function admin_dashboard_kpis()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null or not exists (select 1 from public.admin_roles where user_id = uid) then
    raise exception 'admin_dashboard_kpis: caller is not an admin'
      using errcode = '42501';
  end if;

  return jsonb_build_object(
    'totalUsers',        (select count(*) from public.profiles),
    'totalHouseholds',   (select count(*) from public.households),
    'multiMemberPct',    (
      select coalesce(
        round(100.0 * count(*) filter (where mc > 1) / nullif(count(*), 0), 1),
        0
      )
      from (
        select household_id, count(*) as mc
        from public.memberships
        group by household_id
      ) hh
    ),
    'activeUsers7d',     (
      select count(distinct created_by)
      from public.transactions
      where deleted_at is null
        and created_at >= now() - interval '7 days'
        and created_by is not null
    ),
    'activeHouseholds7d',(
      select count(distinct household_id)
      from public.transactions
      where deleted_at is null
        and created_at >= now() - interval '7 days'
    ),

    'signups7d',         (select count(*) from public.profiles where created_at >= now() - interval '7 days'),
    'signups30d',        (select count(*) from public.profiles where created_at >= now() - interval '30 days'),

    'totalTransactions', (select count(*) from public.transactions where deleted_at is null),
    'transactions7d',    (
      select count(*) from public.transactions
      where deleted_at is null
        and created_at >= now() - interval '7 days'
    ),

    -- Content KPIs
    'publishedArticles', (
      select count(*) from public.content_items
      where deleted_at is null
        and status = 'published'
    ),
    'contentFavorites',  (
      select count(*) from public.content_favorites
      where deleted_at is null
    ),

    -- Subscriptions KPIs (if present)
    'paidSubscriptions', (
      select count(*) from public.subscriptions
      where deleted_at is null
        and status = 'active'
        and tier <> 'free'
    ),
    'mrr', (
      select coalesce(sum(monthly_amount), 0) from public.subscriptions
      where deleted_at is null
        and status = 'active'
        and tier <> 'free'
    ),

    'computedAt',        now()
  );
end;
$$;

grant execute on function admin_dashboard_kpis() to authenticated;

COMMIT;

-- ─────────────────────────────────────────────────────────────────────
-- supabase/migrations/20260524077000_admin_rpcs.sql
-- ─────────────────────────────────────────────────────────────────────
-- Admin-side RPCs for subscription / content lifecycle management.
--
-- Review note (lead, PR #13): the dev who delivered this batch wrote a
-- different RPC set than the one the prompt named — the prompt requested
-- `admin_list_users` / `admin_weekly_trend` / `admin_ai_usage_summary`
-- which plug into the existing admin/src/lib/adminApi.ts fetchers. What
-- landed here is a useful but unrelated set of mutation RPCs:
-- `admin_list_subscriptions`, `admin_cancel_subscription`,
-- `admin_get_mrr_by_currency`, `admin_publish_content_item`,
-- `admin_unpublish_content_item`. Accepted because the work is
-- functionally valuable, but the originally-requested 3 read RPCs
-- remain UNADDRESSED and are re-queued on the lead's workstream.
--
-- Functions are SECURITY DEFINER and validate admin membership via
-- `public.admin_roles`.

BEGIN;

-- List subscriptions (optionally only active)
create or replace function admin_list_subscriptions(active_only boolean default true)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null or not exists (select 1 from public.admin_roles where user_id = uid) then
    raise exception 'admin_list_subscriptions: caller is not an admin' using errcode = '42501';
  end if;

  return (
    select coalesce(jsonb_agg(to_jsonb(s)), '[]'::jsonb)
    from (
      select id, user_id, household_id, tier, status, monthly_amount, currency,
             stripe_subscription_id, started_at, renews_at, failure_count, created_at, updated_at
      from public.subscriptions
      where (not active_only) or (status = 'active')
      order by created_at desc
    ) s
  );
end;
$$;

-- Cancel subscription (admin action)
create or replace function admin_cancel_subscription(sub_id uuid, reason text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
  updated_row jsonb;
begin
  if uid is null or not exists (select 1 from public.admin_roles where user_id = uid) then
    raise exception 'admin_cancel_subscription: caller is not an admin' using errcode='42501';
  end if;

  update public.subscriptions
  set status = 'canceled', updated_at = now(), deleted_at = now()
  where id = sub_id
  returning to_jsonb(public.subscriptions.*) into updated_row;

  if updated_row is null then
    return jsonb_build_object('ok', false, 'message', 'subscription_not_found');
  end if;

  return jsonb_build_object('ok', true, 'subscription', updated_row);
end;
$$;

-- MRR grouped by currency
create or replace function admin_get_mrr_by_currency()
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null or not exists (select 1 from public.admin_roles where user_id = uid) then
    raise exception 'admin_get_mrr_by_currency: caller is not an admin' using errcode='42501';
  end if;

  return (
    select coalesce(jsonb_object_agg(currency, total), '{}'::jsonb)
    from (
      select currency, coalesce(sum(monthly_amount),0) as total
      from public.subscriptions
      where deleted_at is null and status = 'active' and tier <> 'free'
      group by currency
    ) t
  );
end;
$$;

-- Publish a content item (admin action)
create or replace function admin_publish_content_item(content_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
  updated_row jsonb;
begin
  if uid is null or not exists (select 1 from public.admin_roles where user_id = uid) then
    raise exception 'admin_publish_content_item: caller is not an admin' using errcode='42501';
  end if;

  update public.content_items
  set status = 'published', published_at = coalesce(published_at, now()), updated_at = now()
  where id = content_id
  returning to_jsonb(public.content_items.*) into updated_row;

  if updated_row is null then
    return jsonb_build_object('ok', false, 'message', 'content_not_found');
  end if;

  return jsonb_build_object('ok', true, 'content', updated_row);
end;
$$;

-- Unpublish content item (admin action)
create or replace function admin_unpublish_content_item(content_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  uid uuid := auth.uid();
  updated_row jsonb;
begin
  if uid is null or not exists (select 1 from public.admin_roles where user_id = uid) then
    raise exception 'admin_unpublish_content_item: caller is not an admin' using errcode='42501';
  end if;

  update public.content_items
  set status = 'draft', updated_at = now()
  where id = content_id
  returning to_jsonb(public.content_items.*) into updated_row;

  if updated_row is null then
    return jsonb_build_object('ok', false, 'message', 'content_not_found');
  end if;

  return jsonb_build_object('ok', true, 'content', updated_row);
end;
$$;

-- Expose to authenticated callers (function bodies enforce admin membership)
grant execute on function admin_list_subscriptions(boolean) to authenticated;
grant execute on function admin_cancel_subscription(uuid, text) to authenticated;
grant execute on function admin_get_mrr_by_currency() to authenticated;
grant execute on function admin_publish_content_item(uuid) to authenticated;
grant execute on function admin_unpublish_content_item(uuid) to authenticated;

COMMIT;
